id: A422675B8
title: 'Virtuous Adornment for All the World: Verses to Bring Auspiciousness and Wellbeing'
type: translation
pechas:
- IF1F04615
- I95B253A5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:08:03.458171
  last_modified_at: 2023-01-04 12:08:03.458178
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IF1F04615/0227: 7DAD
  I95B253A5/B5BA: 7DAD
